#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Oct 27 12:44:35 CET 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=
