#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 20 22:48:45 CET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=Spooklementary_v2.0.4.zip
